### PR TITLE
Cognite test

### PR DESCRIPTION
**Pull request by chandru4ni**

### CODE REVIEW

**Comment by haakonvt** [comment]
Is this just a test PR @chandru4ni ?

**Comment by chandru4ni** [comment]
Yes, this is a test PR. I need to verify the deployment of Cognite function as part of verification of environment setup on Windows.

**Comment by chandru4ni** [comment]
Can you please approve the review?

**Comment by haakonvt** [comment]
Check out the README file and follow the instructions on how to make your own copy (basically just click "use this template"). Then you can make whatever changes you want.

This repo is the _template repo itself_, so I will not accept these changes to be made here.

**Pull request closed without merging**
